### PR TITLE
Updated readme and added ability to inform users that there are no agents available / online

### PR DESCRIPTION
**Pull request by garypretty**

### CODE REVIEW

**Comment by tompaana** [comment]
Thanks Gary! I happily accept this contribution, but do note that the key functionality will move to https://github.com/tompaana/bot-message-routing/ leaving the command handling etc. here. I'll do my best to migrate all the changes from this there.

**Comment by garypretty** [comment]
Great. Thanks. Look forward to contributing more :)

**Comment by garypretty** [comment]
@tompaana Also, so I understand your strategy correctly. It looks like you are going with having the routing data manager in the new package, which can then use the app setting I have introduced, but then what you do with that command result will be up to you when you implement the message routing result handler in your own solution? Are you not planning to have something like a DefaultMessageRoutingResultHandler present in the new package?

**Comment by tompaana** [comment]
Check out the `development` branch - the answer's there :) In short: No command handling nor result handling (implemented) in the core package. The latter will get an interface though (not sure if that is really required either). The plumbing (commands, result handling) will remain here, but we could figure out together (me, you, other contributors) how to best deal with that.

**Pull request merged**
