### PR TITLE
General tidy up, extracted some methods to clean switch readability, …

### PR DESCRIPTION
**Pull request by garypretty**
…removed unnecessary usings and added missing method docs

### CODE REVIEW

**Comment by daltskin** [comment]
Nice - that was on my TODO list :)

**Comment by garypretty** [comment]
@daltskin :) also added a NoAgentsAvailable result so that if no agents are available then you can let the users know rather than allowing them to request and just sit there. Again, configurable via an app setting.

**Comment by tompaana** [comment]
Apparently you can't review merged PRs so here: Looks good, I approve :)

The thing about the indentation of the preprocessor directives (#pragma etc.) - is there a convention rule about them in C#? In any case we should keep them consistent.

**Comment by garypretty** [comment]
It's just a personal preference. I was also going to ask if you have a preference on use of the car keyword. I use it as standard and finding it hard to remember not to in order to remain in line with you ??

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daltskin** [comment]
You mean var?

Sent from a small telecommunications device.
________________________________

**Comment by garypretty** [comment]
Yes that's what I mean 😁

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tompaana** [comment]
I don't mind `var` here and there as long as one clearly understands the code. I always try to make "code read like a book" and types are sometimes essential for the code to be self-documenting. I started with C/C++ so hence the love of types I guess.

**Pull request merged**
